spring:
  application:
    name: config-project-service
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config

server:
  port: 8888
endpoints:
  restart:
    enabled: true