server:
  port: 8081
  wait-time-in-ms-when-sync-empty: 3000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cliente-service
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
eureka:
  instance:
    hostname: ${DISCOVERY_HOST:localhost}
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
application-version: 2.0.0