server:
  port: 8083
  wait-time-in-ms-when-sync-empty: 3000
spring:
  data:
    mongodb:
      uri: mongodb://adm:root@localhost:27017/ebac?authSource=admin&retryWrites=true&w=majority
      database: vendas-service
      auto-index-creation: true
application:
  produtoService:
    url: http://localhost:8082
    endpointConsultarProduto: ${application.produtoService.url}/produto
  clienteService:
    url: http://localhost:8081
    endpointConsultarCliente: ${application.clienteService.url}/cliente/isCadastrado/{id}
eureka:
  instance:
    hostname: ${DISCOVERY_HOST:localhost}
    port: 9091
  client:
    registerWithEureka: true
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${eureka.instance.port}/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
application-version: 2.0.0